language: node_js
node_js:
  - "14"
branches:
  only:
  - main
script:
  - npm test
  - npm run test:coverage
  - npm run build
deploy:
  on:
    branch: main
  provider: heroku
  app: franco-cicd-project
  api_key:
    secure: RSXT0K6vrBpbfQR8bG7LIZ5IIvXERRfbd7LDO5t5ROoTCS+47U0nTFZ4hNh6MgjynjAwefqrdIaMzW3lLZhxC//4yr5NzIbhJTBj/tJsvdo57UAS+/0fQKV+ICROWb6DnMgS6t/6MPO0JfzLsEygXbCPm11n1mx9hAzkkiHAtSu/WMeNp02d7G0y4VlYi1Z7C7TznCUimln7h5UgYZ1ZJSbbdfvojH7/XnzFnEkY6DlervoB/gbu9kUdW/9mpSdZiWfZEQ5BQZPNds72kWZHovUQXG+i+HQIezLOURaMSAIPIHjEr6mTMWHS4qXflg1S8VNM78UpJFteOOzM4LDGcdXOC8kZIv4lc+UZLCLzICGlWeeNPgpY89CTby6NBtdUPid04lBXbi14HyFlbbb203TRXC2FWNWcJOCsNhgmVTzhArjgEBryOiaZjJn5Pz+KA8MJAzWxIz3eO4svbPOkzlHPTp9nWk7j58ikLv8Jy7UZ8FNiSx36N/dkB2dttvvQ+4MJXqYt9BmGe+9B3JKey3nIt6iPBcMNI9SiugV7/6Jxy4Gzsng2kNtjNIWPG0bJxo0yPRBU6QIKs1/2hhfnCMqperLfyhGab3uGZu3JqrrmIJW9l7dZ5IXVNxFP2gDIGvdiCBR1XzaD2TTezfRfqoJq/LaZzFGpFkPxiHh+ldc=
notifications:
  slack: isutn2021:IYFjFHZOrh5W2EzGpOmhkC4Q